<?xml version="1.0" encoding="utf-8"?><Database Name="EMRDatabase" Class="SiteFunctionsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=shifaaserver.database.windows.net;Initial Catalog=EMRDatabase;Persist Security Info=True;User ID=shifaaAdmin" SettingsObjectName="Shifaa_EMR_System.Properties.Settings" SettingsPropertyName="EMRDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Allergie" Member="Allergies">
    <Type Name="Allergie">
      <Column Name="PatientAllergieID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllergieName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProviderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="AllergiesDatabase_Allergie" Member="AllergiesDatabase" ThisKey="AllergieName" OtherKey="AllergieName" Type="AllergiesDatabase" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Patient_Allergie" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AllergiesDatabase" Member="AllergiesDatabases">
    <Type Name="AllergiesDatabase">
      <Column Name="AllergieName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ColumnNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AllergiesDatabase_Allergie" Member="Allergies" ThisKey="AllergieName" OtherKey="AllergieName" Type="Allergie" />
    </Type>
  </Table>
  <Table Name="dbo.DrugDatabase" Member="DrugDatabases">
    <Type Name="DrugDatabase">
      <Column Name="DrugName" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ColumnName" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="DrugDatabase_Prescription" Member="Prescriptions" ThisKey="DrugName" OtherKey="MedicationName" Type="Prescription" />
    </Type>
  </Table>
  <Table Name="dbo.LabTestNamesDatabase" Member="LabTestNamesDatabases">
    <Type Name="LabTestNamesDatabase">
      <Column Name="LabTestName" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ColumnNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="LabTestNamesDatabase_PatientLab" Member="PatientLabs" ThisKey="LabTestName" OtherKey="LabTestName" Type="PatientLab" />
    </Type>
  </Table>
  <Table Name="dbo.PatientLab" Member="PatientLabs">
    <Type Name="PatientLab">
      <Column Name="PatientLabID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LabTestName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateOrdered" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScheduledDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="LabTestNamesDatabase_PatientLab" Member="LabTestNamesDatabase" ThisKey="LabTestName" OtherKey="LabTestName" Type="LabTestNamesDatabase" IsForeignKey="true" />
      <Association Name="Patient_PatientLab" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientNote" Member="PatientNotes">
    <Type Name="PatientNote">
      <Column Name="NoteID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProviderName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoteTitle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoteContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ColumnNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Patient_PatientNote" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientScan" Member="PatientScans">
    <Type Name="PatientScan">
      <Column Name="PatientScanID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScanName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ScanDetails" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProviderName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateOrdered" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScheduledDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="ProcedureAndScanDatabase_PatientScan" Member="ProcedureAndScanDatabase" ThisKey="ScanName" OtherKey="ProcedureOrScanName" Type="ProcedureAndScanDatabase" IsForeignKey="true" />
      <Association Name="Patient_PatientScan" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Prescription" Member="Prescriptions">
    <Type Name="Prescription">
      <Column Name="PrescriptionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MedicationName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Strength" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Route" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Refills" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ProviderName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DateStopped" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DrugDatabase_Prescription" Member="DrugDatabase" ThisKey="MedicationName" OtherKey="DrugName" Type="DrugDatabase" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Patient_Prescription" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProcedureAndScanDatabase" Member="ProcedureAndScanDatabases">
    <Type Name="ProcedureAndScanDatabase">
      <Column Name="ProcedureOrScanName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ColumnNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ProcedureAndScanDatabase_PatientScan" Member="PatientScans" ThisKey="ProcedureOrScanName" OtherKey="ScanName" Type="PatientScan" />
    </Type>
  </Table>
  <Table Name="dbo.SchedulerHashTable" Member="SchedulerHashTables">
    <Type Name="SchedulerHashTable">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SchedulerHash" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Association Name="SchedulerHashTable_SchedulerInfo" Member="SchedulerInfo" ThisKey="Username" OtherKey="Username" Type="SchedulerInfo" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.ProviderHashTable" Member="ProviderHashTables">
    <Type Name="ProviderHashTable">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderHash" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Association Name="ProviderHashTable_Physician_Login_Info" Member="Physician_Login_Info" ThisKey="Username" OtherKey="USERNAME" Type="Physician_Login_Info" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Problem" Member="Problems">
    <Type Name="Problem">
      <Column Name="ProblemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProblemName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ProblemDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateDiagnosed" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DateResolved" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProviderName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProviderID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Association Name="ProblemListDatabase_Problem" Member="ProblemListDatabase" ThisKey="ProblemName" OtherKey="ProblemName" Type="ProblemListDatabase" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Patient_Problem" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProblemListDatabase" Member="ProblemListDatabases">
    <Type Name="ProblemListDatabase">
      <Column Name="ProblemName" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ColumnRowNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="ProblemListDatabase_Problem" Member="Problems" ThisKey="ProblemName" OtherKey="ProblemName" Type="Problem" />
    </Type>
  </Table>
  <Table Name="dbo.VitalSigns" Member="VitalSigns">
    <Type Name="VitalSign">
      <Column Name="VitalSignID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BloodPressure" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Pulse" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Temperature" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BMI" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DateUpdated" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Patient_VitalSign" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="ColumnNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaritalStatus" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PregnancyStatus" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Weight" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Height" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="BMI" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Nationality" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Patient_Allergie" Member="Allergies" ThisKey="PatientID" OtherKey="PatientID" Type="Allergie" />
      <Association Name="Patient_PatientLab" Member="PatientLabs" ThisKey="PatientID" OtherKey="PatientID" Type="PatientLab" />
      <Association Name="Patient_PatientNote" Member="PatientNotes" ThisKey="PatientID" OtherKey="PatientID" Type="PatientNote" />
      <Association Name="Patient_PatientScan" Member="PatientScans" ThisKey="PatientID" OtherKey="PatientID" Type="PatientScan" />
      <Association Name="Patient_Prescription" Member="Prescriptions" ThisKey="PatientID" OtherKey="PatientID" Type="Prescription" />
      <Association Name="Patient_Problem" Member="Problems" ThisKey="PatientID" OtherKey="PatientID" Type="Problem" />
      <Association Name="Patient_VitalSign" Member="VitalSigns" ThisKey="PatientID" OtherKey="PatientID" Type="VitalSign" />
      <Association Name="Patient_PatientProviderRelation" Member="PatientProviderRelations" ThisKey="PatientID" OtherKey="PatientID" Type="PatientProviderRelation" />
      <Association Name="Patient_Appointment" Member="Appointments" ThisKey="PatientID" OtherKey="patientID" Type="Appointment" />
    </Type>
  </Table>
  <Table Name="dbo.SchedulerHashTable" Member="SchedulerHashTable1s">
    <Type Name="SchedulerHashTable1">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SchedulerHash" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Association Name="SchedulerHashTable1_SchedulerInfo" Member="SchedulerInfo" ThisKey="Username" OtherKey="Username" Type="SchedulerInfo" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Physician_Login_Info" Member="Physician_Login_Infos">
    <Type Name="Physician_Login_Info">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="JobRole" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Physician_Login_Info_SchedulersBelongingToProvider" Member="SchedulersBelongingToProviders" ThisKey="USERNAME" OtherKey="ProviderID" Type="SchedulersBelongingToProvider" />
      <Association Name="Physician_Login_Info_PatientProviderRelation" Member="PatientProviderRelations" ThisKey="USERNAME" OtherKey="ProviderID" Type="PatientProviderRelation" />
      <Association Name="Physician_Login_Info_Appointment" Member="Appointments" ThisKey="USERNAME" OtherKey="ProviderID" Type="Appointment" />
      <Association Name="ProviderHashTable_Physician_Login_Info" Member="ProviderHashTable" ThisKey="USERNAME" OtherKey="Username" Type="ProviderHashTable" IsForeignKey="true" />
      <Association Name="AllEmployee_Physician_Login_Info" Member="AllEmployee" ThisKey="USERNAME" OtherKey="EmployeeID" Type="AllEmployee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchedulerInfo" Member="SchedulerInfos">
    <Type Name="SchedulerInfo">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JobRole" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="SchedulerInfo_SchedulersBelongingToProvider" Member="SchedulersBelongingToProviders" ThisKey="Username" OtherKey="SchedulerID" Type="SchedulersBelongingToProvider" />
      <Association Name="SchedulerHashTable_SchedulerInfo" Member="SchedulerHashTable" ThisKey="Username" OtherKey="Username" Type="SchedulerHashTable" IsForeignKey="true" />
      <Association Name="SchedulerHashTable1_SchedulerInfo" Member="SchedulerHashTable1" ThisKey="Username" OtherKey="Username" Type="SchedulerHashTable1" IsForeignKey="true" />
      <Association Name="AllEmployee_SchedulerInfo" Member="AllEmployee" ThisKey="Username" OtherKey="EmployeeID" Type="AllEmployee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AllEmployees" Member="AllEmployees">
    <Type Name="AllEmployee">
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderOrScheduler" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JobType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="AllEmployee_Physician_Login_Info" Member="Physician_Login_Info" ThisKey="EmployeeID" OtherKey="USERNAME" Type="Physician_Login_Info" Cardinality="One" />
      <Association Name="AllEmployee_SchedulerInfo" Member="SchedulerInfo" ThisKey="EmployeeID" OtherKey="Username" Type="SchedulerInfo" Cardinality="One" />
      <Association Name="AllEmployee_Message" Member="Messages" ThisKey="EmployeeID" OtherKey="SenderID" Type="Message" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Messages">
    <Type Name="Message">
      <Column Name="MessageIDNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SenderName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SenderID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecipientName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecipientID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateTimeDraft" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateTimeSent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MessageTitle" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MessageContent" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="AllEmployee_Message" Member="AllEmployee" ThisKey="SenderID" OtherKey="EmployeeID" Type="AllEmployee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchedulersBelongingToProvider" Member="SchedulersBelongingToProviders">
    <Type Name="SchedulersBelongingToProvider">
      <Column Name="RowNum" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProviderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SchedulerID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProviderName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Physician_Login_Info_SchedulersBelongingToProvider" Member="Physician_Login_Info" ThisKey="ProviderID" OtherKey="USERNAME" Type="Physician_Login_Info" IsForeignKey="true" />
      <Association Name="SchedulerInfo_SchedulersBelongingToProvider" Member="SchedulerInfo" ThisKey="SchedulerID" OtherKey="Username" Type="SchedulerInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientProviderRelation" Member="PatientProviderRelations">
    <Type Name="PatientProviderRelation">
      <Column Name="RowNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PatientFirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PatientLastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderFirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderLastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderJobType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProviderTitle" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Patient_PatientProviderRelation" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" />
      <Association Name="Physician_Login_Info_PatientProviderRelation" Member="Physician_Login_Info" ThisKey="ProviderID" OtherKey="USERNAME" Type="Physician_Login_Info" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="appointmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="patientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProviderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Pattern" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PatternColor" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Patient_Appointment" Member="Patient" ThisKey="patientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Physician_Login_Info_Appointment" Member="Physician_Login_Info" ThisKey="ProviderID" OtherKey="USERNAME" Type="Physician_Login_Info" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.getNewPatientVitals" Method="getNewPatientVitals">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DOB" Parameter="dOB" Type="System.DateTime" DbType="Date" />
    <ElementType Name="getNewPatientVitalsResult">
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getCurrentPatientVitals" Method="getCurrentPatientVitals">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <ElementType Name="getCurrentPatientVitalsResult">
      <Column Name="BloodPressure" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Pulse" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Temperature" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Height" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Weight" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="BMI" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DateUpdated" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getPatientNote" Method="getPatientNote">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NoteTitle" Parameter="noteTitle" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="getPatientNoteResult">
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoteTitle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoteContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProviderName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.deleteAppointment" Method="deleteAppointment">
    <Parameter Name="AppointmentID" Parameter="appointmentID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deletePatientAllergy" Method="deletePatientAllergy">
    <Parameter Name="PatientAllergyID" Parameter="patientAllergyID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteVitalSigns" Method="deleteVitalSigns">
    <Parameter Name="VitalSignsID" Parameter="vitalSignsID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deletePatientLab" Method="deletePatientLab">
    <Parameter Name="PatientLabID" Parameter="patientLabID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deletePatientPrescription" Method="deletePatientPrescription">
    <Parameter Name="PrescriptionID" Parameter="prescriptionID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deletePatientScan" Method="deletePatientScan">
    <Parameter Name="ScanID" Parameter="scanID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteProblem" Method="deleteProblem">
    <Parameter Name="ProblemID" Parameter="problemID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateExistingProblem" Method="updateExistingProblem">
    <Parameter Name="ProblemID" Parameter="problemID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProblemName" Parameter="problemName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ProblemDescription" Parameter="problemDescription" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="UpdateDate" Parameter="updateDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.selectMedicationForReport" Method="selectMedicationForReport">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <ElementType Name="selectMedicationForReportResult">
      <Column Name="MedicationName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Strength" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Route" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Refills" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectProblemsForReport" Method="selectProblemsForReport">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <ElementType Name="selectProblemsForReportResult">
      <Column Name="ProblemName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ProblemDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateDiagnosed" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectNotesForReport" Method="selectNotesForReport">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <ElementType Name="selectNotesForReportResult">
      <Column Name="NoteTitle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoteContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getPatientByID" Method="getPatientByID">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <ElementType Name="getPatientByIDResult">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaritalStatus" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PregnancyStatus" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.updatePrescription" Method="updatePrescription">
    <Parameter Name="PrescriptionID" Parameter="prescriptionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MedicationName" Parameter="medicationName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Amount" Parameter="amount" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Strength" Parameter="strength" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Route" Parameter="route" Type="System.String" DbType="NChar(30)" />
    <Parameter Name="Frequency" Parameter="frequency" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Refills" Parameter="refills" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="DateStopped" Parameter="dateStopped" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.selectPrescriptionforPrint" Method="selectPrescriptionforPrint">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <ElementType Name="selectPrescriptionforPrintResult">
      <Column Name="MedicationName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Strength" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Route" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Refills" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.updateExistingNote" Method="updateExistingNote">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NoteTitle" Parameter="noteTitle" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NoteContent" Parameter="noteContent" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deletePatientNote" Method="deletePatientNote">
    <Parameter Name="NoteID" Parameter="noteID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.authenticateProvider" Method="authenticateProvider">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Passcode" Parameter="passcode" Type="System.String" DbType="VarChar(32)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createLatestVitalSign" Method="createLatestVitalSign">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="BloodPressure" Parameter="bloodPressure" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pulse" Parameter="pulse" Type="System.Double" DbType="Float" />
    <Parameter Name="Temperature" Parameter="temperature" Type="System.Double" DbType="Float" />
    <Parameter Name="Height" Parameter="height" Type="System.Double" DbType="Float" />
    <Parameter Name="Weight" Parameter="weight" Type="System.Double" DbType="Float" />
    <Parameter Name="BMI" Parameter="bMI" Type="System.Double" DbType="Float" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createNewAllergy" Method="createNewAllergy">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AllergieName" Parameter="allergieName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Details" Parameter="details" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ProviderID" Parameter="providerID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProviderName" Parameter="providerName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createNewLabOrder" Method="createNewLabOrder">
    <Parameter Name="LabTestName" Parameter="labTestName" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="ProviderName" Parameter="providerName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProviderID" Parameter="providerID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ScheduledDate" Parameter="scheduledDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createNewPatientNote" Method="createNewPatientNote">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProviderName" Parameter="providerName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProviderID" Parameter="providerID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NoteTitle" Parameter="noteTitle" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NoteContent" Parameter="noteContent" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createNewPrescription" Method="createNewPrescription">
    <Parameter Name="MedicationName" Parameter="medicationName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Amount" Parameter="amount" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Strength" Parameter="strength" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Route" Parameter="route" Type="System.String" DbType="NChar(30)" />
    <Parameter Name="Frequency" Parameter="frequency" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Refills" Parameter="refills" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProviderName" Parameter="providerName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProviderID" Parameter="providerID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createNewProblem" Method="createNewProblem">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProblemName" Parameter="problemName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Details" Parameter="details" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ProviderID" Parameter="providerID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProviderName" Parameter="providerName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createNewScanOrProcedureOrder" Method="createNewScanOrProcedureOrder">
    <Parameter Name="ScanName" Parameter="scanName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ScanDetails" Parameter="scanDetails" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ProviderName" Parameter="providerName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProviderID" Parameter="providerID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ScheduledDate" Parameter="scheduledDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createNewVitalSign" Method="createNewVitalSign">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="BloodPressure" Parameter="bloodPressure" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pulse" Parameter="pulse" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Temperature" Parameter="temperature" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Height" Parameter="height" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Weight" Parameter="weight" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="BMI" Parameter="bMI" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getLatestPatientVitals" Method="getLatestPatientVitals">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <ElementType Name="getLatestPatientVitalsResult">
      <Column Name="BloodPressure" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Pulse" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Temperature" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BMI" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DateUpdated" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.createNewPatient" Method="createNewPatient">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PhoneNumber" Parameter="phoneNumber" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="DOB" Parameter="dOB" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Age" Parameter="age" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="MaritalStatus" Parameter="maritalStatus" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PregnancyStatus" Parameter="pregnancyStatus" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Weight" Parameter="weight" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Height" Parameter="height" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="BMI" Parameter="bMI" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Nationality" Parameter="nationality" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CreateAppointment" Method="CreateAppointment">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Details" Parameter="details" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="StartDateTime" Parameter="startDateTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EndDateTime" Parameter="endDateTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Provider" Parameter="provider" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sendMessageToJunk" Method="sendMessageToJunk">
    <Parameter Name="MessageID" Parameter="messageID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.convertNameToID" Method="convertNameToID">
    <Parameter Name="FirtName" Parameter="firtName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="JobTitle" Parameter="jobTitle" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="convertNameToIDResult">
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SendMessage" Method="SendMessage">
    <Parameter Name="SenderID" Parameter="senderID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SenderName" Parameter="senderName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MessageTitle" Parameter="messageTitle" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="MessageContent" Parameter="messageContent" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="DateTime" Parameter="dateTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="RecipientName" Parameter="recipientName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RecipientID" Parameter="recipientID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="MessageID" Parameter="messageID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.convertIDToName" Method="convertIDToName">
    <Parameter Name="EmployeeID" Parameter="employeeID" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="convertIDToNameResult">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.updateMessageDraft" Method="updateMessageDraft">
    <Parameter Name="SenderID" Parameter="senderID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SenderName" Parameter="senderName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MessageTitle" Parameter="messageTitle" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="MessageContent" Parameter="messageContent" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="DateTime" Parameter="dateTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="RecipientName" Parameter="recipientName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RecipientID" Parameter="recipientID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createProviderSchedulerRelation" Method="createProviderSchedulerRelation">
    <Parameter Name="ProviderID" Parameter="providerID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProviderName" Parameter="providerName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SchedulerID" Parameter="schedulerID" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getJustCreatedAppointmentID" Method="getJustCreatedAppointmentID">
    <ElementType Name="getJustCreatedAppointmentIDResult">
      <Column Name="appointmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="patientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.editAppointment" Method="editAppointment">
    <Parameter Name="appointmentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Details" Parameter="details" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="StartTime" Parameter="startTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EndTime" Parameter="endTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProviderID" Parameter="providerID" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createPatientProviderRelation" Method="createPatientProviderRelation">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProviderID" Parameter="providerID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProviderFirstName" Parameter="providerFirstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProviderLastName" Parameter="providerLastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProviderTitle" Parameter="providerTitle" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="ProviderJobType" Parameter="providerJobType" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getPatientID" Method="getPatientID">
    <Parameter Name="PatientFirstName" Parameter="patientFirstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PatientLastName" Parameter="patientLastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DOB" Parameter="dOB" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="getPatientIDResult">
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getProviderInfo" Method="getProviderInfo">
    <Parameter Name="ProviderUserName" Parameter="providerUserName" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="getProviderInfoResult">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="JobRole" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.updateAppointmentStatus" Method="updateAppointmentStatus">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="AppointmentID" Parameter="appointmentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Color" Parameter="color" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Pattern" Parameter="pattern" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PatternColor" Parameter="patternColor" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getAppointmentForCurrentProvider" Method="getAppointmentForCurrentProvider">
    <Parameter Name="ProviderID" Parameter="providerID" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="getAppointmentForCurrentProviderResult">
      <Column Name="appointmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="patientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProviderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Pattern" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PatternColor" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAppointmentsForCurrentPatient" Method="getAppointmentsForCurrentPatient">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <ElementType Name="getAppointmentsForCurrentPatientResult">
      <Column Name="appointmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="patientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProviderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Pattern" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PatternColor" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.createProviderAccount" Method="createProviderAccount">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="PhoneNumber" Parameter="phoneNumber" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="JobType" Parameter="jobType" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Passcode1" Parameter="passcode1" Type="System.String" DbType="VarChar(32)" />
    <Parameter Name="Passcode2" Parameter="passcode2" Type="System.String" DbType="VarChar(32)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createSchedulerAccount" Method="createSchedulerAccount">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PhoneNumber" Parameter="phoneNumber" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Passcode1" Parameter="passcode1" Type="System.String" DbType="VarChar(32)" />
    <Parameter Name="Passcode2" Parameter="passcode2" Type="System.String" DbType="VarChar(32)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.authenticateScheduler" Method="authenticateScheduler">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Passcode" Parameter="passcode" Type="System.String" DbType="VarChar(32)" />
    <Return Type="System.Int32" />
  </Function>
</Database>