<?xml version="1.0" encoding="utf-8"?><Database Name="EMRDatabase" Class="SiteFunctionsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=shifaaserver.database.windows.net;Initial Catalog=EMRDatabase;Persist Security Info=True;User ID=shifaaAdmin" SettingsObjectName="Shifaa_EMR_System.Properties.Settings" SettingsPropertyName="EMRDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="appointmentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateAppointment" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TimeAppointment" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DurationAppointment" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="patientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Column Number]" Member="Column_Number" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Patient_Appointment" Member="Patient" ThisKey="patientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="ColumnNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Height" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BMI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Nationality" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Patient_Appointment" Member="Appointments" ThisKey="PatientID" OtherKey="patientID" Type="Appointment" />
      <Association Name="Patient_PatientNote" Member="PatientNotes" ThisKey="PatientID" OtherKey="PatientID" Type="PatientNote" />
      <Association Name="Patient_VitalSign" Member="VitalSigns" ThisKey="PatientID" OtherKey="PatientID" Type="VitalSign" />
      <Association Name="Patient_Prescription" Member="Prescriptions" ThisKey="PatientID" OtherKey="PatientID" Type="Prescription" />
    </Type>
  </Table>
  <Table Name="dbo.PatientNote" Member="PatientNotes">
    <Type Name="PatientNote">
      <Column Name="NoteID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProviderName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoteTitle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoteContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ColumnNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Patient_PatientNote" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VitalSigns" Member="VitalSigns">
    <Type Name="VitalSign">
      <Column Name="VitalSignID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BloodPressure" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Pulse" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Temperature" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Height" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BMI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DateUpdated" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Patient_VitalSign" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MedicationDatabase" Member="MedicationDatabases">
    <Type Name="MedicationDatabase">
      <Column Name="MedicationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GenericName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BrandNames" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="MedicationDatabase_Prescription" Member="Prescriptions" ThisKey="MedicationID" OtherKey="MedicationID" Type="Prescription" />
    </Type>
  </Table>
  <Table Name="dbo.Prescription" Member="Prescriptions">
    <Type Name="Prescription">
      <Column Name="PrescriptionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MedicationName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MedicationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Strength" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Route" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Refills" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MedicationDatabase_Prescription" Member="MedicationDatabase" ThisKey="MedicationID" OtherKey="MedicationID" Type="MedicationDatabase" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Patient_Prescription" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.CreateAppointment" Method="CreateAppointment">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Details" Parameter="details" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="DateAppointment" Parameter="dateAppointment" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TimeAppointment" Parameter="timeAppointment" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="DurationAppointment" Parameter="durationAppointment" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createNewVitalSign" Method="createNewVitalSign">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <Parameter Name="BloodPressure" Parameter="bloodPressure" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pulse" Parameter="pulse" Type="System.Double" DbType="Float" />
    <Parameter Name="Temperature" Parameter="temperature" Type="System.Double" DbType="Float" />
    <Parameter Name="Height" Parameter="height" Type="System.Double" DbType="Float" />
    <Parameter Name="Weight" Parameter="weight" Type="System.Double" DbType="Float" />
    <Parameter Name="BMI" Parameter="bMI" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.createNewPatient" Method="createNewPatient">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PhoneNumber" Parameter="phoneNumber" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="DOB" Parameter="dOB" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Age" Parameter="age" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="Char(10)" />
    <Parameter Name="Weight" Parameter="weight" Type="System.Double" DbType="Float" />
    <Parameter Name="Height" Parameter="height" Type="System.Double" DbType="Float" />
    <Parameter Name="BMI" Parameter="bMI" Type="System.Double" DbType="Float" />
    <Parameter Name="Nationality" Parameter="nationality" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getPatientVitals" Method="getPatientVitals">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.Int32" DbType="Int" />
    <ElementType Name="getPatientVitalsResult">
      <Column Name="BloodPressure" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Pulse" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Temperature" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Height" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BMI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DateUpdated" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>